CREATE TABLE tl_ebgi_def.tb_t_co_insurer_list_hist (
  source_app_code string,
  dml_ind string,
  record_created_date timestamp,
  record_updated_date timestamp,
  record_created_by string,
  record_updated_by string,
  record_eff_from_date timestamp,
  record_eff_to_date timestamp,
  active_record_ind string,
  checksum string,
  change_seq decimal(38, 0),
  uuid string,
  business_key string,
  co_list_id decimal(10, 0),
  policy_general_uuid string,
  policy_id decimal(10, 0),
  co_share decimal(6, 4),
  ref_policy_no string,
  leader_flag decimal(1, 0),
  insert_time timestamp,
  party_id decimal(10, 0),
  si_share decimal(12, 2),
  commision_share decimal(12, 2),
  other_fee decimal(12, 2),
  co_fee_rate decimal(6, 4),
  update_time timestamp,
  field01 string,
  field02 string,
  field03 string,
  field04 string,
  field05 string,
  field06 string,
  field07 string,
  field08 string,
  field09 string,
  field10 string,
  field11 string,
  field12 string,
  field13 string,
  field14 string,
  field15 string,
  field16 string,
  field17 string,
  field18 string,
  field19 string,
  field20 string)
PARTITIONED BY (`active_record_ind`, bucket(8, `business_key`))
LOCATION 's3://datalake-tds-dev-income-com-sg/datalake_tds/tl_ebgi_def/tb_t_co_insurer_list_hist'
TBLPROPERTIES (
  'table_type'='iceberg',
  'optimize_rewrite_max_data_file_size_bytes'='262144001',
  'write_compression'='zstd',
  'format'='parquet',
  'write_target_data_file_size_bytes'='145635556'
);